### ISSUE TITLE
Outdated addresses on RSK docs

### ISSUE THREAD

**Issue by pmprete** [covalenthq/covalent-docs#159]
The addresses shown in https://www.covalenthq.com/docs/networks/rsk/#rsk-smart-contract-address-mapping are outdated compared to https://developers.rsk.co/tools/tokenbridge/contractaddresses/

This PR fixes it https://github.com/covalenthq/covalent-docs/pull/158

**Comment by emmaodia** [comment]
[Fix](https://github.com/covalenthq/covalent-docs/pull/158)
