### ISSUE TITLE
How can I use covalent API to get specific transaction?

### ISSUE THREAD

**Issue by zydjohnHotmail** [covalenthq/covalent-docs#259]
Hello:
I have done one traction at beginning of last month, I can find the transaction ID from the original exchange. The transaction # TxID
0x4f951e6ba3817a2cc9f52b6ab2d5e07e9bc69212be0a314e6b4ffce095864e19
But with the following URL, I can not find details about this transaction.
curl -X GET https://api.covalenthq.com/v1/1/transaction_v2/0x4f951e6ba3817a2cc9f52b6ab2d5e07e9bc69212be0a314e6b4ffce095864e19/
-u user_name: -H 'Content-Type: application/json'
I got the following response:
{
	"data": null,
	"error": true,
	"error_message": "Transaction not found with hash: 0x4f951e6ba3817a2cc9f52b6ab2d5e07e9bc69212be0a314e6b4ffce095864e19",
	"error_code": 404
}
Let me know how can I find the transaction.
By the way, this transaction was done via HECO network.
Please advise,

**Comment by harishraisinghani** [comment]
Hi, in your curl example, the `chain_id` being used is 1 which is for Ethereum mainnet, not HECO mainnet. 

Try it with a `chain_id` of 128:

curl -X GET https://api.covalenthq.com/v1/128/transaction_v2/0x4f951e6ba3817a2cc9f52b6ab2d5e07e9bc69212be0a314e6b4ffce095864e19/?quote-currency=USD&format=JSON&no-logs=false&key=<YOUR API KEY>
